sonar.projectKey=iers-frontend
sonar.projectName=iers-frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions de couverture
sonar.coverage.exclusions=\
  **/app/**,\
  **/pages/**,\
  **/components/**,\
  **/layouts/**,\
  **/context/**,\
  **/hooks/**,\
  **/assets/**,\
  **/main.tsx,\
  **/vite-env.d.ts,\
  **/__mocks__/**

sonar.typescript.node.maxspace=1024
sonar.javascript.node.maxspace=1024